#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
gmx_interaction_rerun.py

Interactive GROMACS workflow for:
1) building membrane-region index groups (head / fence / tail / mem),
2) preparing a rerun TPR with gmx grompp,
3) recalculating trajectory energies with gmx mdrun -rerun,
4) extracting energy terms interactively with gmx energy,
5) converting XVG output to Excel (.xlsx).

Design principles:
- Numeric menus are used whenever possible; users do not need to type lipid
  residue names or atom names.
- Invalid input does not terminate the program; the current step is repeated.
- The script preserves the default groups generated by gmx make_ndx and adds
  four custom groups: head, fence, tail, mem.
- head/fence/tail are enforced to be mutually exclusive.
- mem intentionally contains all selected lipid atoms and therefore overlaps
  with head/fence/tail. Do NOT use mem together with head/fence/tail in the
  same energygrps line. Use a separate rerun if total membrane interaction
  and regional decomposition are both required.
- CPU nonbonded calculation (-nb cpu) is used for rerun because GROMACS
  energy-group decomposition is not supported on GPU nonbonded kernels in
  current GROMACS versions.

Python requirement: Python 3.8+
External requirement: GROMACS ("gmx" or "gmx_mpi")
No third-party Python package is required. If openpyxl is installed it will
be used; otherwise the script writes a minimal valid XLSX using the standard
library.
"""

from __future__ import annotations

import math
import re
import shlex
import shutil
import subprocess
import sys
import zipfile
from collections import Counter, OrderedDict, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple
from xml.sax.saxutils import escape as xml_escape


OUTPUT_INDEX = "index.ndx"
RERUN_PREFIX = "rerun"
DEFAULT_THREADS = 24
DEFAULT_MAXWARN = 4
FORCE_CPU_FOR_ENERGY_GROUPS = True
TRAJECTORY_EXTENSIONS = {".xtc", ".trr", ".tng"}
CUSTOM_GROUPS = ("head", "fence", "tail", "mem")

PROTEIN_RESIDUES = {
    "ALA", "ARG", "ASN", "ASP", "ASH", "CYS", "CYM", "CYX", "GLN", "GLU",
    "GLH", "GLY", "HIS", "HID", "HIE", "HIP", "ILE", "LEU", "LYS", "LYN",
    "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL",
    "HSD", "HSE", "HSP", "ACE", "NME", "NH2", "NTER", "CTER",
}
WATER_RESIDUES = {
    "SOL", "WAT", "HOH", "TIP3", "TIP3P", "TIP4P", "SPC", "SPCE", "PW",
}
ION_RESIDUES = {
    "NA", "NA+", "SOD", "K", "K+", "POT", "CL", "CL-", "CLA",
    "CA", "CA2", "MG", "MG2", "ZN", "ZN2", "LI", "CS",
}


def hr(char: str = "=", width: int = 78) -> None:
    print(char * width)


def section(title: str) -> None:
    print()
    hr("=")
    print(title)
    hr("=")


def info(msg: str) -> None:
    print(f"[INFO] {msg}")


def warn(msg: str) -> None:
    print(f"[WARNING] {msg}")


def error(msg: str) -> None:
    print(f"[ERROR] {msg}")


def success(msg: str) -> None:
    print(f"[OK] {msg}")


def ask_yes_no(prompt: str, default: Optional[bool] = None) -> bool:
    while True:
        suffix = " [y/n]: "
        if default is True:
            suffix = " [Y/n]: "
        elif default is False:
            suffix = " [y/N]: "

        ans = input(prompt + suffix).strip().lower()
        if not ans and default is not None:
            return default
        if ans in {"y", "yes", "1"}:
            return True
        if ans in {"n", "no", "0"}:
            return False
        warn("Invalid input. Please enter y/yes or n/no.")


def ask_nonempty(prompt: str, default: Optional[str] = None) -> str:
    while True:
        suffix = f" [{default}]: " if default else ": "
        ans = input(prompt + suffix).strip()
        if not ans and default is not None:
            ans = default
        if ans:
            return ans
        warn("Input cannot be empty. Please try again.")


def parse_number_selection(
    text: str,
    max_number: int,
    *,
    allow_all: bool = True,
    allow_empty: bool = False,
) -> Optional[List[int]]:
    s = text.strip().lower()
    if not s:
        return [] if allow_empty else None

    if allow_all and s in {"all", "a", "*"}:
        return list(range(1, max_number + 1))

    selected: Set[int] = set()
    tokens = [t for t in s.replace(",", " ").split() if t]
    try:
        for token in tokens:
            if "-" in token:
                parts = token.split("-", 1)
                if len(parts) != 2 or not parts[0] or not parts[1]:
                    return None
                start, end = int(parts[0]), int(parts[1])
                if start > end:
                    start, end = end, start
                if start < 1 or end > max_number:
                    return None
                selected.update(range(start, end + 1))
            else:
                n = int(token)
                if n < 1 or n > max_number:
                    return None
                selected.add(n)
    except ValueError:
        return None

    if not selected and not allow_empty:
        return None
    return sorted(selected)


def ask_number_selection(
    prompt: str,
    max_number: int,
    *,
    allow_all: bool = True,
    allow_empty: bool = False,
) -> List[int]:
    while True:
        parsed = parse_number_selection(
            input(prompt),
            max_number,
            allow_all=allow_all,
            allow_empty=allow_empty,
        )
        if parsed is not None:
            return parsed
        examples = "1 2 5 / 1-3,7"
        if allow_all:
            examples += " / all"
        if allow_empty:
            examples += " / Enter=skip"
        warn(f"Invalid selection. Examples: {examples}")


def validate_gmx_command(prefix: Sequence[str]) -> bool:
    try:
        result = subprocess.run(
            list(prefix) + ["--version"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        if result.returncode == 0 and "GROMACS" in (result.stdout or "").upper():
            first_line = next(
                (line.strip() for line in result.stdout.splitlines() if line.strip()),
                "GROMACS detected",
            )
            success(first_line)
            return True
    except (OSError, FileNotFoundError):
        pass
    return False


def detect_gmx() -> List[str]:
    section("GROMACS DETECTION")
    for name in ("gmx", "gmx_mpi", "gmx_d"):
        exe = shutil.which(name)
        if exe and validate_gmx_command([exe]):
            return [exe]

    warn("Could not automatically find gmx/gmx_mpi in PATH.")
    while True:
        cmd = ask_nonempty(
            "Enter the GROMACS command or executable path "
            "(e.g. gmx or /usr/local/bin/gmx)"
        )
        try:
            prefix = shlex.split(cmd)
        except ValueError:
            warn("Could not parse the command. Please try again.")
            continue
        if prefix and validate_gmx_command(prefix):
            return prefix
        error("This command is not a working GROMACS executable. Re-enter it.")


def command_string(cmd: Sequence[str]) -> str:
    return " ".join(shlex.quote(str(x)) for x in cmd)


def run_command(
    cmd: Sequence[str],
    *,
    input_text: Optional[str] = None,
    interactive: bool = False,
) -> int:
    print()
    print("$ " + command_string(cmd))
    try:
        if interactive:
            result = subprocess.run(list(cmd), check=False)
        else:
            result = subprocess.run(
                list(cmd),
                input=input_text,
                text=(input_text is not None),
                check=False,
            )
        return int(result.returncode)
    except KeyboardInterrupt:
        print()
        warn("Command interrupted by user.")
        return 130
    except OSError as exc:
        error(f"Could not start command: {exc}")
        return 127


def discover_files(extensions: Set[str]) -> List[Path]:
    files = [
        p for p in Path.cwd().iterdir()
        if p.is_file() and p.suffix.lower() in extensions
    ]
    return sorted(files, key=lambda p: (p.suffix.lower(), p.name.lower()))


def choose_file(
    label: str,
    extensions: Set[str],
    *,
    preferred: Optional[Path] = None,
) -> Path:
    while True:
        section(f"DATA SELECTION — {label}")
        candidates = discover_files(extensions)

        if preferred is not None:
            pref_resolved = preferred.resolve()
            candidates = sorted(
                candidates,
                key=lambda p: (p.resolve() != pref_resolved, p.name.lower()),
            )

        if candidates:
            for i, path in enumerate(candidates, 1):
                tags = []
                if preferred is not None and path.resolve() == preferred.resolve():
                    tags.append("recommended")
                if path.name.startswith(RERUN_PREFIX):
                    tags.append("rerun-related")
                tag_text = f"  [{' | '.join(tags)}]" if tags else ""
                size_mb = path.stat().st_size / (1024 * 1024)
                print(f"{i:>3}. {path.name:<40} {size_mb:>10.3f} MB{tag_text}")

            if len(candidates) == 1:
                if ask_yes_no(f"Use {candidates[0].name}?", default=True):
                    return candidates[0].resolve()
            else:
                while True:
                    ans = input(
                        f"Select {label} by number, or M for manual path: "
                    ).strip().lower()
                    if ans in {"m", "manual"}:
                        break
                    try:
                        n = int(ans)
                        if 1 <= n <= len(candidates):
                            return candidates[n - 1].resolve()
                    except ValueError:
                        pass
                    warn("Invalid selection. Enter a displayed number or M.")

        else:
            warn(
                f"No {label} file detected in {Path.cwd()}. "
                f"Expected: {', '.join(sorted(extensions))}"
            )

        manual = ask_nonempty(f"Enter the path to the {label}")
        p = Path(manual).expanduser()
        if p.is_file() and p.suffix.lower() in extensions:
            return p.resolve()
        error(
            "File does not exist or has the wrong extension. "
            f"Expected: {', '.join(sorted(extensions))}"
        )


def parse_gro(gro_path: Path) -> Tuple[str, List[dict], str]:
    try:
        lines = gro_path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as exc:
        raise ValueError(f"Could not read GRO file: {exc}") from exc

    if len(lines) < 3:
        raise ValueError("GRO file is too short.")

    try:
        natoms = int(lines[1].strip())
    except ValueError as exc:
        raise ValueError("Second line of GRO is not a valid atom count.") from exc

    if len(lines) < natoms + 3:
        raise ValueError(
            f"GRO says {natoms} atoms but not enough atom lines are present."
        )

    atoms: List[dict] = []
    for seq, line in enumerate(lines[2:2 + natoms], start=1):
        if len(line) < 20:
            raise ValueError(f"Malformed GRO atom line at sequential atom {seq}.")
        resname = line[5:10].strip()
        atomname = line[10:15].strip()
        if not resname or not atomname:
            raise ValueError(
                f"Could not parse residue/atom name at sequential atom {seq}."
            )
        try:
            resid = int(line[0:5].strip())
        except ValueError:
            resid = None
        atoms.append(
            {
                "index": seq,  # NDX uses sequential atom order, starting at 1.
                "resid": resid,
                "resname": resname,
                "atomname": atomname,
            }
        )

    box_line = lines[2 + natoms]
    return lines[0], atoms, box_line


def gro_signature(gro_path: Path) -> Tuple[int, Tuple[Tuple[str, str], ...]]:
    _, atoms, _ = parse_gro(gro_path)
    return len(atoms), tuple((a["resname"], a["atomname"]) for a in atoms)


def read_ndx(path: Path) -> "OrderedDict[str, List[int]]":
    groups: "OrderedDict[str, List[int]]" = OrderedDict()
    current: Optional[str] = None
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            m = re.match(r"^\[\s*(.*?)\s*\]$", line)
            if m:
                current = m.group(1)
                groups[current] = []
                continue
            if current is None:
                continue
            for token in line.split():
                try:
                    groups[current].append(int(token))
                except ValueError:
                    pass
    return groups


def write_ndx(path: Path, groups: "OrderedDict[str, List[int]]") -> None:
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        for name, atom_indices in groups.items():
            fh.write(f"[ {name} ]\n")
            atoms = sorted(dict.fromkeys(atom_indices))
            for i in range(0, len(atoms), 15):
                fh.write(" ".join(f"{n:6d}" for n in atoms[i:i + 15]) + "\n")
            fh.write("\n")


def remove_groups_case_insensitive(
    groups: "OrderedDict[str, List[int]]",
    names: Iterable[str],
) -> "OrderedDict[str, List[int]]":
    remove = {x.lower() for x in names}
    out: "OrderedDict[str, List[int]]" = OrderedDict()
    for name, atoms in groups.items():
        if name.lower() not in remove:
            out[name] = atoms
    return out


def find_group_case_insensitive(
    groups: Dict[str, List[int]],
    name: str,
) -> Optional[str]:
    for existing in groups:
        if existing.lower() == name.lower():
            return existing
    return None


def residue_statistics(
    atoms: Sequence[dict],
) -> Tuple[List[str], Dict[str, int], Dict[str, int]]:
    first_order: List[str] = []
    seen: Set[str] = set()
    atom_counts: Dict[str, int] = Counter()
    block_counts: Dict[str, int] = Counter()

    prev = None
    for atom in atoms:
        resname = atom["resname"]
        if resname not in seen:
            seen.add(resname)
            first_order.append(resname)
        atom_counts[resname] += 1
        key = (atom["resid"], resname)
        if key != prev:
            block_counts[resname] += 1
            prev = key

    return first_order, dict(block_counts), dict(atom_counts)


def is_candidate_lipid_residue(resname: str) -> bool:
    up = resname.upper()
    return (
        up not in PROTEIN_RESIDUES
        and up not in WATER_RESIDUES
        and up not in ION_RESIDUES
    )


def choose_lipid_residue_types(atoms: Sequence[dict]) -> List[str]:
    section("STEP 1 — SELECT LIPID RESIDUE TYPES")
    order, molecule_counts, atom_counts = residue_statistics(atoms)
    candidates = [r for r in order if is_candidate_lipid_residue(r)]
    if not candidates:
        warn("No candidates remained after protein/water/ion filtering.")
        candidates = list(order)

    while True:
        print(
            "\nCandidate residue types "
            "(choose lipids by NUMBER; do not type residue names):"
        )
        for i, resname in enumerate(candidates, 1):
            print(
                f"{i:>3}. {resname:<10} "
                f"residue-blocks={molecule_counts.get(resname, 0):<6} "
                f"atoms={atom_counts.get(resname, 0)}"
            )

        print(
            "\nCommands: numbers/ranges = select; A = all candidates; "
            "S = show all residue types"
        )
        ans = input("Select all lipid residue types: ").strip()

        if ans.lower() in {"s", "show", "showall"}:
            print("\nAll residue types in the GRO file:")
            for i, resname in enumerate(order, 1):
                category = []
                if resname.upper() in PROTEIN_RESIDUES:
                    category.append("protein")
                if resname.upper() in WATER_RESIDUES:
                    category.append("water")
                if resname.upper() in ION_RESIDUES:
                    category.append("ion")
                tag = f" [{' / '.join(category)}]" if category else ""
                print(
                    f"{i:>3}. {resname:<10} "
                    f"residue-blocks={molecule_counts.get(resname, 0):<6} "
                    f"atoms={atom_counts.get(resname, 0)}{tag}"
                )
            nums = ask_number_selection(
                "Select lipid residue types from ALL residues: ",
                len(order),
                allow_all=True,
            )
            selected = [order[i - 1] for i in nums]
        else:
            nums = parse_number_selection(
                ans, len(candidates), allow_all=True, allow_empty=False
            )
            if nums is None:
                warn("Invalid selection. Choose by number/range, A, or S.")
                continue
            selected = [candidates[i - 1] for i in nums]

        print("\nSelected lipid residue types: " + ", ".join(selected))
        if ask_yes_no("Confirm these lipid residue types?", default=True):
            return selected


def unique_atom_names_for_residue(
    atoms: Sequence[dict],
    resname: str,
) -> Tuple[List[str], Dict[str, int]]:
    order: List[str] = []
    seen: Set[str] = set()
    counts: Dict[str, int] = Counter()
    for atom in atoms:
        if atom["resname"] != resname:
            continue
        name = atom["atomname"]
        counts[name] += 1
        if name not in seen:
            seen.add(name)
            order.append(name)
    return order, dict(counts)


def region_map_to_encoded(region_map: Dict[str, Set[str]]) -> Set[str]:
    return {
        f"{resname}\0{atomname}"
        for resname, atomnames in region_map.items()
        for atomname in atomnames
    }


def select_region_atoms(
    atoms: Sequence[dict],
    lipid_resnames: Sequence[str],
    region: str,
    already_assigned: Dict[str, Set[str]],
) -> Dict[str, Set[str]]:
    section(f"STEP 2 — DEFINE {region.upper()} REGION")
    region_map: Dict[str, Set[str]] = {}

    for resname in lipid_resnames:
        names, counts = unique_atom_names_for_residue(atoms, resname)

        while True:
            print(f"\n{region.upper()} atoms for lipid {resname}")
            print(
                "Choose by NUMBER. Press Enter to assign no atoms from this "
                "lipid to this region."
            )
            for i, atomname in enumerate(names, 1):
                encoded = f"{resname}\0{atomname}"
                occupied_by = [
                    r for r, occupied in already_assigned.items()
                    if encoded in occupied
                ]
                tag = (
                    f"  [already in {', '.join(occupied_by)}]"
                    if occupied_by else ""
                )
                print(
                    f"{i:>3}. {atomname:<10} "
                    f"occurrences={counts.get(atomname, 0):<6}{tag}"
                )

            nums = ask_number_selection(
                f"Select {resname} atoms for {region}: ",
                len(names),
                allow_all=True,
                allow_empty=True,
            )
            selected_names = {names[i - 1] for i in nums}

            bad = []
            for atomname in selected_names:
                encoded = f"{resname}\0{atomname}"
                if any(encoded in occupied for occupied in already_assigned.values()):
                    bad.append(atomname)

            if bad:
                error(
                    "These atom names are already assigned to another region: "
                    + ", ".join(sorted(bad))
                )
                warn("Re-enter this lipid's selection.")
                continue

            region_map[resname] = selected_names
            break

    total = {
        atom["index"]
        for atom in atoms
        if atom["resname"] in region_map
        and atom["atomname"] in region_map[atom["resname"]]
    }

    if not total:
        warn(f"The {region} group is empty. Define it again.")
        return select_region_atoms(
            atoms, lipid_resnames, region, already_assigned
        )

    print(f"\n{region} region summary:")
    for resname in lipid_resnames:
        chosen = sorted(region_map.get(resname, set()))
        print(f"  {resname:<10}: {', '.join(chosen) if chosen else '(none)'}")
    print(f"  Total atoms in [{region}]: {len(total)}")

    if not ask_yes_no(f"Confirm the {region} definition?", default=True):
        return select_region_atoms(
            atoms, lipid_resnames, region, already_assigned
        )
    return region_map


def atom_indices_from_region_map(
    atoms: Sequence[dict],
    region_map: Dict[str, Set[str]],
) -> List[int]:
    return [
        atom["index"]
        for atom in atoms
        if atom["resname"] in region_map
        and atom["atomname"] in region_map[atom["resname"]]
    ]


def show_unassigned_lipid_atoms(
    atoms: Sequence[dict],
    lipid_resnames: Sequence[str],
    region_maps: Dict[str, Dict[str, Set[str]]],
) -> bool:
    assigned: Dict[str, Set[str]] = defaultdict(set)
    for region_map in region_maps.values():
        for resname, names in region_map.items():
            assigned[resname].update(names)

    unassigned: Dict[str, List[str]] = {}
    for resname in lipid_resnames:
        names, _ = unique_atom_names_for_residue(atoms, resname)
        missing = [n for n in names if n not in assigned[resname]]
        if missing:
            unassigned[resname] = missing

    if not unassigned:
        success("Every selected lipid atom name is assigned to head/fence/tail.")
        return True

    warn(
        "Some lipid atom names are not assigned to head/fence/tail. "
        "They remain in [mem] but are excluded from regional groups:"
    )
    for resname, names in unassigned.items():
        print(f"  {resname:<10}: {', '.join(names)}")
    return ask_yes_no("Continue with these unassigned atoms?", default=False)


def build_custom_index(
    gmx: Sequence[str],
    gro_path: Path,
    output_index: Path,
) -> Path:
    section("INDEX CONSTRUCTION")
    while True:
        try:
            _, atoms, _ = parse_gro(gro_path)
            break
        except ValueError as exc:
            error(str(exc))
            gro_path = choose_file(
                "GRO structure for index construction", {".gro"}
            )

    lipid_resnames = choose_lipid_residue_types(atoms)

    while True:
        head_map = select_region_atoms(
            atoms, lipid_resnames, "head", already_assigned={}
        )
        fence_map = select_region_atoms(
            atoms,
            lipid_resnames,
            "fence",
            already_assigned={"head": region_map_to_encoded(head_map)},
        )
        tail_map = select_region_atoms(
            atoms,
            lipid_resnames,
            "tail",
            already_assigned={
                "head": region_map_to_encoded(head_map),
                "fence": region_map_to_encoded(fence_map),
            },
        )
        region_maps = {
            "head": head_map,
            "fence": fence_map,
            "tail": tail_map,
        }
        if show_unassigned_lipid_atoms(atoms, lipid_resnames, region_maps):
            break
        warn("Restarting head/fence/tail assignment.")

    head_atoms = atom_indices_from_region_map(atoms, head_map)
    fence_atoms = atom_indices_from_region_map(atoms, fence_map)
    tail_atoms = atom_indices_from_region_map(atoms, tail_map)
    lipid_set = set(lipid_resnames)
    mem_atoms = [a["index"] for a in atoms if a["resname"] in lipid_set]

    hs, fs, ts = set(head_atoms), set(fence_atoms), set(tail_atoms)
    if hs & fs or hs & ts or fs & ts:
        raise RuntimeError("Internal error: head/fence/tail atom groups overlap.")

    temp_ndx = Path.cwd() / ".gmx_interaction_base.ndx"
    if temp_ndx.exists():
        try:
            temp_ndx.unlink()
        except OSError:
            pass

    section("RUNNING GMX MAKE_NDX")
    cmd = list(gmx) + [
        "make_ndx", "-f", str(gro_path), "-o", str(temp_ndx)
    ]

    while True:
        rc = run_command(cmd, input_text="q\n")
        if rc == 0 and temp_ndx.is_file() and temp_ndx.stat().st_size > 0:
            break
        error("gmx make_ndx did not generate the temporary index file.")
        if not ask_yes_no("Retry gmx make_ndx?", default=True):
            gro_path = choose_file(
                "GRO structure for index construction", {".gro"}
            )
            return build_custom_index(gmx, gro_path, output_index)

    groups = read_ndx(temp_ndx)
    groups = remove_groups_case_insensitive(groups, CUSTOM_GROUPS)
    groups["head"] = head_atoms
    groups["fence"] = fence_atoms
    groups["tail"] = tail_atoms
    groups["mem"] = mem_atoms

    while True:
        try:
            write_ndx(output_index, groups)
            break
        except OSError as exc:
            error(f"Could not write {output_index}: {exc}")
            name = ask_nonempty(
                "Enter another NDX output filename",
                default="interaction_index.ndx",
            )
            output_index = Path(name)
            if output_index.suffix.lower() != ".ndx":
                output_index = output_index.with_suffix(".ndx")

    try:
        temp_ndx.unlink()
    except OSError:
        pass

    section("INDEX SUMMARY")
    print(f"Output : {output_index.resolve()}")
    print(f"[head ]: {len(head_atoms):>8} atoms")
    print(f"[fence]: {len(fence_atoms):>8} atoms")
    print(f"[tail ]: {len(tail_atoms):>8} atoms")
    print(f"[mem  ]: {len(mem_atoms):>8} atoms")
    print("Lipids : " + ", ".join(lipid_resnames))
    success("Custom membrane index groups generated.")
    warn(
        "[mem] overlaps with [head]/[fence]/[tail] by design. "
        "Do not use mem together with regional groups in one energygrps line."
    )
    return output_index.resolve()


def parse_mdp(path: Path) -> Dict[str, str]:
    opts: Dict[str, str] = {}
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.split(";", 1)[0].strip()
            if not line or "=" not in line:
                continue
            key, value = line.split("=", 1)
            normalized = re.sub(r"[-_]", "", key.strip().lower())
            opts[normalized] = value.strip()
    return opts


def split_mdp_group_names(value: str) -> List[str]:
    return [x for x in value.split() if x]


def validate_energygrps(mdp_path: Path, ndx_path: Path) -> bool:
    try:
        opts = parse_mdp(mdp_path)
    except OSError as exc:
        error(f"Could not read MDP: {exc}")
        return False

    value = opts.get("energygrps", "").strip()
    if not value:
        error(
            "No non-empty 'energygrps = ...' was found in this MDP."
        )
        return False

    if "," in value:
        error(
            "Commas are not valid separators in energygrps. "
            "Use spaces, e.g. energygrps = LIG head fence tail"
        )
        return False

    energygrps = split_mdp_group_names(value)
    print("energygrps = " + " ".join(energygrps))
    if len(energygrps) < 2:
        error("At least two groups are required for an intermolecular pair.")
        return False

    low = {g.lower() for g in energygrps}
    if "mem" in low and low.intersection({"head", "fence", "tail"}):
        error(
            "mem overlaps with head/fence/tail. Use either:\n"
            "  regional mode: energygrps = LIG head fence tail\n"
            "or\n"
            "  total-membrane mode: energygrps = LIG mem"
        )
        return False

    groups = read_ndx(ndx_path)
    for required in CUSTOM_GROUPS:
        if find_group_case_insensitive(groups, required) is None:
            error(f"Required custom group [{required}] is missing.")
            return False

    resolved: List[Tuple[str, Set[int]]] = []
    for requested in energygrps:
        real = find_group_case_insensitive(groups, requested)
        if real is None:
            warn(
                f"'{requested}' is not explicitly present in the NDX. "
                "It may still be a valid topology/molecule-type group; "
                "grompp will make the final check."
            )
        else:
            resolved.append((requested, set(groups[real])))

    overlaps = []
    for i in range(len(resolved)):
        for j in range(i + 1, len(resolved)):
            n = len(resolved[i][1] & resolved[j][1])
            if n:
                overlaps.append((resolved[i][0], resolved[j][0], n))

    if overlaps:
        error("Overlapping energy groups detected:")
        for a, b, n in overlaps:
            print(f"  {a} <-> {b}: {n} shared atoms")
        return False

    for key in ("nstenergy", "nstcalcenergy"):
        raw = opts.get(key)
        if raw:
            try:
                val = int(float(raw.split()[0]))
                if val != 1:
                    warn(
                        f"{key} = {val}. For frame-wise rerun output, "
                        f"{key} = 1 is often convenient."
                    )
            except ValueError:
                pass

    success("MDP energygrps validation passed.")
    return True


def ensure_mdp_ready(mdp_path: Path, ndx_path: Path) -> bool:
    while True:
        if validate_energygrps(mdp_path, ndx_path):
            return True
        print("\nPlease correct the current MDP/index or select other inputs.")
        print("  1. I corrected the current file(s); re-check")
        print("  2. Re-select input files")
        while True:
            ans = input("Choose 1 or 2: ").strip()
            if ans == "1":
                break
            if ans == "2":
                return False
            warn("Invalid input. Enter 1 or 2.")


def validate_gro_compatibility(index_gro: Path, rerun_gro: Path) -> bool:
    try:
        n1, sig1 = gro_signature(index_gro)
        n2, sig2 = gro_signature(rerun_gro)
    except ValueError as exc:
        error(f"Could not compare GRO files: {exc}")
        return False

    if n1 != n2:
        error(
            f"Atom-count mismatch: index GRO={n1}; grompp GRO={n2}."
        )
        return False

    if sig1 != sig2:
        mismatch = next(
            (i for i, (a, b) in enumerate(zip(sig1, sig2), 1) if a != b),
            None,
        )
        error(
            "Atom-name/residue-name ordering differs between index GRO "
            "and grompp GRO."
        )
        if mismatch is not None:
            print(
                f"First mismatch at atom {mismatch}: "
                f"{sig1[mismatch-1]} vs {sig2[mismatch-1]}"
            )
        return False

    success("Index GRO and grompp GRO atom ordering are compatible.")
    return True


def file_state(path: Path) -> Optional[Tuple[int, int]]:
    try:
        st = path.stat()
        return st.st_mtime_ns, st.st_size
    except OSError:
        return None


def output_is_new_or_updated(
    path: Path,
    before: Optional[Tuple[int, int]],
) -> bool:
    after = file_state(path)
    if after is None or after[1] <= 0:
        return False
    return before is None or after != before


def select_rerun_inputs(
    generated_index: Path,
) -> Tuple[Path, Path, Path, Path]:
    mdp_pref = (
        Path("rerun.mdp").resolve()
        if Path("rerun.mdp").is_file()
        else None
    )
    mdp = choose_file("MDP file for rerun", {".mdp"}, preferred=mdp_pref)
    top = choose_file("TOP topology", {".top"})
    gro = choose_file("GRO coordinate file for grompp", {".gro"})
    ndx = choose_file(
        "NDX index file", {".ndx"}, preferred=generated_index
    )
    return mdp, top, gro, ndx


def build_rerun_tpr(
    gmx: Sequence[str],
    index_gro: Path,
    generated_index: Path,
) -> Path:
    section("STEP 3 — PREPARE RERUN TPR")

    while True:
        mdp, top, gro, ndx = select_rerun_inputs(generated_index)

        try:
            groups = read_ndx(ndx)
        except OSError as exc:
            error(f"Could not read NDX: {exc}")
            continue

        missing = [
            name for name in CUSTOM_GROUPS
            if find_group_case_insensitive(groups, name) is None
        ]
        if missing:
            error(
                "Selected NDX is missing: " + ", ".join(missing)
            )
            continue

        if not validate_gro_compatibility(index_gro, gro):
            warn("Re-selecting inputs.")
            continue

        if not ensure_mdp_ready(mdp, ndx):
            continue

        tpr = Path.cwd() / f"{RERUN_PREFIX}.tpr"
        before = file_state(tpr)
        cmd = list(gmx) + [
            "grompp",
            "-f", str(mdp),
            "-c", str(gro),
            "-p", str(top),
            "-o", str(tpr),
            "-n", str(ndx),
            "-maxwarn", str(DEFAULT_MAXWARN),
        ]

        section("RUNNING GMX GROMPP")
        rc = run_command(cmd)
        if rc == 0 and output_is_new_or_updated(tpr, before):
            success(f"Generated {tpr.name}")
            return tpr.resolve()

        error("gmx grompp did not generate/update rerun.tpr.")
        print(
            "Review the GROMACS message above. The script will return to "
            "file/MDP selection instead of exiting."
        )
        input("Press Enter to continue...")


def choose_trajectory() -> Path:
    section("STEP 4 — SELECT TRAJECTORY FOR RERUN")
    candidates = discover_files(TRAJECTORY_EXTENSIONS)

    if candidates:
        preferred = next((p for p in candidates if p.name == "md.xtc"), None)
        if preferred is None:
            non_rerun = [
                p for p in candidates if not p.name.startswith(RERUN_PREFIX)
            ]
            pool = non_rerun or candidates
            preferred = max(pool, key=lambda p: p.stat().st_mtime)

        print("Detected trajectory files:")
        for i, p in enumerate(candidates, 1):
            tag = (
                "  [suggested/current]"
                if p.resolve() == preferred.resolve()
                else ""
            )
            size_mb = p.stat().st_size / (1024 * 1024)
            print(f"{i:>3}. {p.name:<40} {size_mb:>10.3f} MB{tag}")

        if ask_yes_no(
            f"Rerun '{preferred.name}'?",
            default=True,
        ):
            return preferred.resolve()

    return choose_file("trajectory for rerun", TRAJECTORY_EXTENSIONS)


def run_rerun(
    gmx: Sequence[str],
    tpr: Path,
) -> Tuple[Path, Path]:
    trajectory = choose_trajectory()
    edr = Path.cwd() / f"{RERUN_PREFIX}.edr"

    while True:
        before = file_state(edr)
        cmd = list(gmx) + [
            "mdrun",
            "-v",
            "-deffnm", RERUN_PREFIX,
            "-rerun", str(trajectory),
            "-e", str(edr),
            "-ntmpi", "1",
            "-ntomp", str(DEFAULT_THREADS),
        ]
        if FORCE_CPU_FOR_ENERGY_GROUPS:
            cmd += ["-nb", "cpu"]

        section("RUNNING GMX MDRUN -RERUN")
        if FORCE_CPU_FOR_ENERGY_GROUPS:
            info(
                "Using -nb cpu for GROMACS energy-group decomposition."
            )

        rc = run_command(cmd)
        if rc == 0 and output_is_new_or_updated(edr, before):
            success(f"Rerun completed: {edr.name}")
            return edr.resolve(), trajectory

        error("rerun.edr was not successfully generated/updated.")
        if ask_yes_no("Retry with the SAME trajectory?", default=True):
            continue
        trajectory = choose_trajectory()


def parse_xvg(
    path: Path,
) -> Tuple[List[str], List[List[object]], List[str]]:
    legends: Dict[int, str] = {}
    metadata: List[str] = []
    rows: List[List[object]] = []
    x_label = "X"

    legend_re = re.compile(r'@\s+s(\d+)\s+legend\s+"(.*)"')
    xlabel_re = re.compile(r'@\s+xaxis\s+label\s+"(.*)"')

    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            if line.startswith("#") or line.startswith("@"):
                metadata.append(line)
                m = legend_re.search(line)
                if m:
                    legends[int(m.group(1))] = m.group(2)
                m = xlabel_re.search(line)
                if m:
                    x_label = m.group(1)
                continue

            row: List[object] = []
            valid = True
            for token in line.split():
                try:
                    value = float(token)
                    if math.isnan(value) or math.isinf(value):
                        row.append(token)
                    else:
                        row.append(value)
                except ValueError:
                    valid = False
                    break
            if valid and row:
                rows.append(row)

    if not rows:
        raise ValueError("No numeric data rows found in XVG.")

    max_cols = max(len(r) for r in rows)
    headers = [x_label or "X"]
    for col in range(1, max_cols):
        headers.append(legends.get(col - 1, f"Series_{col}"))
    for row in rows:
        row.extend([""] * (max_cols - len(row)))
    return headers, rows, metadata


def excel_col_letter(n: int) -> str:
    result = ""
    while n:
        n, rem = divmod(n - 1, 26)
        result = chr(65 + rem) + result
    return result


def cell_xml(ref: str, value: object) -> str:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if isinstance(value, float) and (
            math.isnan(value) or math.isinf(value)
        ):
            text = xml_escape(str(value))
            return (
                f'<c r="{ref}" t="inlineStr"><is><t>{text}</t></is></c>'
            )
        return f'<c r="{ref}"><v>{value}</v></c>'
    text = xml_escape("" if value is None else str(value))
    return f'<c r="{ref}" t="inlineStr"><is><t>{text}</t></is></c>'


def rows_to_sheet_xml(rows: Sequence[Sequence[object]]) -> str:
    xml_rows = []
    for r_idx, row in enumerate(rows, 1):
        cells = []
        for c_idx, value in enumerate(row, 1):
            ref = f"{excel_col_letter(c_idx)}{r_idx}"
            cells.append(cell_xml(ref, value))
        xml_rows.append(f'<row r="{r_idx}">{"".join(cells)}</row>')
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/'
        'spreadsheetml/2006/main"><sheetData>'
        + "".join(xml_rows)
        + '</sheetData></worksheet>'
    )


def write_minimal_xlsx(
    xlsx_path: Path,
    headers: Sequence[str],
    rows: Sequence[Sequence[object]],
    metadata: Sequence[str],
) -> None:
    data_rows = [list(headers)] + [list(r) for r in rows]
    meta_rows = [["XVG metadata/comments"]] + [[x] for x in metadata]

    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>"""

    root_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""

    workbook = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
 xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheets>
<sheet name="Data" sheetId="1" r:id="rId1"/>
<sheet name="Metadata" sheetId="2" r:id="rId2"/>
</sheets>
</workbook>"""

    workbook_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>
</Relationships>"""

    with zipfile.ZipFile(
        xlsx_path, "w", compression=zipfile.ZIP_DEFLATED
    ) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", root_rels)
        zf.writestr("xl/workbook.xml", workbook)
        zf.writestr("xl/_rels/workbook.xml.rels", workbook_rels)
        zf.writestr(
            "xl/worksheets/sheet1.xml", rows_to_sheet_xml(data_rows)
        )
        zf.writestr(
            "xl/worksheets/sheet2.xml", rows_to_sheet_xml(meta_rows)
        )


def convert_xvg_to_xlsx(
    xvg_path: Path,
    xlsx_path: Optional[Path] = None,
) -> Path:
    if xlsx_path is None:
        xlsx_path = xvg_path.with_suffix(".xlsx")
    headers, rows, metadata = parse_xvg(xvg_path)

    try:
        from openpyxl import Workbook  # type: ignore

        wb = Workbook()
        ws = wb.active
        ws.title = "Data"
        ws.append(list(headers))
        for row in rows:
            ws.append(list(row))
        ws.freeze_panes = "A2"

        meta = wb.create_sheet("Metadata")
        meta.append(["XVG metadata/comments"])
        for line in metadata:
            meta.append([line])
        wb.save(xlsx_path)
    except ImportError:
        write_minimal_xlsx(xlsx_path, headers, rows, metadata)

    if not xlsx_path.is_file() or xlsx_path.stat().st_size <= 0:
        raise OSError("XLSX output was not created correctly.")
    return xlsx_path


def extract_energy_and_convert(
    gmx: Sequence[str],
    edr: Path,
) -> List[Tuple[Path, Path]]:
    outputs: List[Tuple[Path, Path]] = []

    section("STEP 5 — GMX ENERGY EXTRACTION")
    print(
        "gmx energy will display all available energy terms.\n"
        "Select the required terms directly in the GROMACS prompt. For membrane\n"
        "interaction decomposition, common targets include Coul-SR and LJ-SR\n"
        "for the desired group pairs. Finish the GROMACS selection with 0 or\n"
        "according to the prompt shown by your GROMACS version."
    )

    while True:
        default_stem = (
            "interaction_energy"
            if not outputs
            else f"interaction_energy_{len(outputs)+1}"
        )
        stem = ask_nonempty(
            "Output name for this extraction (without .xvg)",
            default=default_stem,
        )
        xvg = Path(stem)
        if xvg.suffix.lower() != ".xvg":
            xvg = xvg.with_suffix(".xvg")
        if not xvg.is_absolute():
            xvg = (Path.cwd() / xvg).resolve()

        before = file_state(xvg)
        cmd = list(gmx) + [
            "energy", "-f", str(edr), "-o", str(xvg)
        ]

        section("INTERACTIVE GMX ENERGY")
        info("Select the desired energy terms in the GROMACS screen now.")
        rc = run_command(cmd, interactive=True)

        if rc != 0 or not output_is_new_or_updated(xvg, before):
            error("gmx energy did not generate/update the requested XVG.")
            if ask_yes_no("Retry this extraction?", default=True):
                continue
            if not ask_yes_no(
                "Continue to another energy extraction?", default=False
            ):
                break
            continue

        success(f"Generated {xvg.name}")

        xlsx = xvg.with_suffix(".xlsx")
        while True:
            try:
                xlsx = convert_xvg_to_xlsx(xvg, xlsx)
                success(f"Converted to Excel: {xlsx.name}")
                break
            except Exception as exc:
                error(f"XVG -> Excel conversion failed: {exc}")
                if not ask_yes_no("Retry conversion?", default=True):
                    warn("Continuing without a confirmed XLSX conversion.")
                    break

        outputs.append((xvg, xlsx))

        if not ask_yes_no(
            "Extract another set of energy terms from rerun.edr?",
            default=False,
        ):
            break

    return outputs


def main() -> int:
    section(
        "GROMACS INTERMOLECULAR INTERACTION / MEMBRANE-REGION RERUN"
    )
    print(
        "The script builds head/fence/tail/mem groups, prepares rerun.tpr,\n"
        "reruns an existing trajectory to obtain rerun.edr, extracts selected\n"
        "energy terms, and converts XVG output to Excel.\n"
        "Invalid user input is requested again instead of terminating."
    )

    gmx = detect_gmx()

    index_gro = choose_file(
        "GRO structure for index construction", {".gro"}
    )
    generated_index = build_custom_index(
        gmx, index_gro, Path.cwd() / OUTPUT_INDEX
    )

    section("RERUN MDP REMINDER")
    print(
        "Before grompp, the rerun MDP must contain the group names to decompose.\n"
        "Example for regional decomposition:\n"
        "    energygrps = LIG head fence tail\n"
        "Example for whole-membrane interaction (separate rerun):\n"
        "    energygrps = LIG mem\n"
        "Replace LIG with the actual interacting molecule/group name."
    )
    if not ask_yes_no(
        "Have you already rewritten/checked the rerun MDP and added "
        "the required group names?",
        default=True,
    ):
        warn(
            "The script will keep re-checking the selected MDP until a valid "
            "energygrps setting is found."
        )

    tpr = build_rerun_tpr(gmx, index_gro, generated_index)
    edr, trajectory = run_rerun(gmx, tpr)
    outputs = extract_energy_and_convert(gmx, edr)

    section("WORKFLOW COMPLETED")
    print(f"Index file : {generated_index}")
    print(f"Rerun TPR  : {tpr}")
    print(f"Trajectory : {trajectory}")
    print(f"Energy file: {edr}")
    if outputs:
        print("Extracted outputs:")
        for xvg, xlsx in outputs:
            print(f"  XVG  : {xvg}")
            print(f"  Excel: {xlsx}")
    else:
        warn("No gmx energy XVG output was confirmed.")

    print()
    hr("*")
    print("CONGRATULATIONS!")
    hr("*")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print()
        warn("Program stopped by user (Ctrl+C).")
        sys.exit(130)
